# Generated by Django 5.1.1 on 2024-10-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='FirstName', max_length=20, unique=True, verbose_name='Name')),
                ('lastname', models.CharField(blank=True, max_length=20, verbose_name='Surname')),
                ('address', models.CharField(max_length=50)),
                ('phnno', models.BigIntegerField(default=0, verbose_name='Phone Number')),
            ],
            options={
                'db_table': 'modelFormapp_Customer',
            },
        ),
    ]
