# Generated by Django 5.1.1 on 2024-10-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50, unique=True)),
                ('completion_status', models.CharField(choices=[('not_completed', 'Not Completed'), ('completed', 'Completed'), ('on_going', 'On going')], default='not_completed', max_length=15)),
                ('due_date', models.DateField()),
            ],
        ),
    ]
