# Generated by Django 5.1.1 on 2024-10-28 11:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, unique=True)),
                ('genre', models.CharField(max_length=40)),
                ('duration', models.IntegerField()),
                ('release_date', models.DateField()),
                ('ratings', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Films',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketapp.movie')),
            ],
            options={
                'verbose_name': 'Showtime',
                'verbose_name_plural': 'Showtimes',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=5)),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked')], max_length=10)),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketapp.showtime')),
            ],
            options={
                'verbose_name': 'Seat',
                'verbose_name_plural': 'Seats',
                'ordering': ['seat_number'],
                'unique_together': {('showtime', 'seat_number')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketapp.seat')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketapp.showtime')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['showtime', 'seat'],
                'unique_together': {('showtime', 'seat')},
            },
        ),
    ]
