# Generated by Django 5.1.1 on 2024-10-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True, verbose_name='Title')),
                ('author', models.CharField(max_length=20, verbose_name='Author')),
                ('isbn', models.BigIntegerField(default=0, unique=True, verbose_name='ISBN')),
                ('genre', models.CharField(max_length=20, verbose_name='Genre')),
            ],
            options={
                'db_table': 'libraryapp_Library',
            },
        ),
    ]
