# Generated by Django 5.1.1 on 2024-11-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='images',
            field=models.ImageField(default=None, null=True, upload_to='images'),
        ),
    ]
